max_retries = 3
timeout = 20

accept = [
  "200..=299",
  "301",
  "302",
  "303",
  "307",
  "308",
  "403",
  "429"
]

include_mail = false
exclude_loopback = true

exclude = [
  '^https://scholar\.google\.com/',
  '^https://www\.researchgate\.net/',
  '^https://www\.google\.com/maps/'
]
